/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentregistration;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import studentregistration_without_db.*;
import studentregistration.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Maruf
 */
public class StudentRegistrationJFrame extends javax.swing.JFrame {

    /**
     * Creates new form StudentRegistrationJFrame
     */
    public StudentRegistrationJFrame() {
        initComponents();
        showStudentList();

    }

    public ArrayList<Student> getStudentList() {

        ArrayList<Student> studentList = new ArrayList<Student>();

        Connection connection = JavaConnectDB.getConnection();

        String query = "SELECT * FROM  student";
        Statement st;
        ResultSet rs;

        try {
            st = connection.createStatement();
            rs = st.executeQuery(query);

            Student student;
            while (rs.next()) {
                student = new Student(rs.getString("NAME"), rs.getString("DEPARTMENT"), rs.getString("SID"));
                studentList.add(student);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
        System.out.println(studentList);
        return studentList;
    }

    public void showStudentList() {

        ArrayList<Student> list = getStudentList();
        DefaultTableModel model = (DefaultTableModel) jTable_Student.getModel();
        Object[] row = new Object[3];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getName();
            row[1] = list.get(i).getDepartment();
            row[2] = list.get(i).getSid();

            model.addRow(row);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Student = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jText_SName = new javax.swing.JTextField();
        jText_SId = new javax.swing.JTextField();
        jCombo_SDept = new javax.swing.JComboBox();
        jButton_Insert = new javax.swing.JButton();
        jButton_Update = new javax.swing.JButton();
        jButton_Delete = new javax.swing.JButton();
        ErrorMessages = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable_Student.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student Name", "Department", "Student Id"
            }
        ));
        jTable_Student.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_StudentMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Student);

        jLabel1.setText("Student Name:");

        jLabel2.setText("Student Department:");

        jLabel3.setText("Student Id:");

        jCombo_SDept.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CSE", "EEE", "MCE", "CIVIL" }));

        jButton_Insert.setText("Insert");
        jButton_Insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_InsertActionPerformed(evt);
            }
        });

        jButton_Update.setText("Update");
        jButton_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_UpdateActionPerformed(evt);
            }
        });

        jButton_Delete.setText("Delete");
        jButton_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DeleteActionPerformed(evt);
            }
        });

        ErrorMessages.setForeground(new java.awt.Color(255, 0, 0));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("STUDENT MANAGEMENT SYSTEM");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jCombo_SDept, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ErrorMessages, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jButton_Insert)
                                            .addGap(30, 30, 30)
                                            .addComponent(jButton_Update)
                                            .addGap(24, 24, 24)
                                            .addComponent(jButton_Delete))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addGap(48, 48, 48)
                                            .addComponent(jText_SName, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(3, 3, 3))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jText_SId, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 65, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jText_SName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCombo_SDept, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jText_SId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Insert)
                    .addComponent(jButton_Update)
                    .addComponent(jButton_Delete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ErrorMessages, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_InsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_InsertActionPerformed
        // TODO add your handling code here:
        ErrorMessages.setText("");

        String query = "INSERT INTO STUDENT(NAME, DEPARTMENT, SID) VALUES ('" + jText_SName.getText() + "','" + jCombo_SDept.getSelectedItem() + "'," + jText_SId.getText() + ")";

        Connection con = JavaConnectDB.getConnection();
        Statement st;

        DefaultTableModel model = (DefaultTableModel) jTable_Student.getModel();
        if (!jText_SName.getText().trim().equals("")) {
            try {
                st = con.createStatement();
                if ((st.executeUpdate(query)) == 1) {
                    model.setRowCount(0);
                    showStudentList();
                    ErrorMessages.setText("Student Information Successfully Inserted");
                } else {
                    ErrorMessages.setText("Student Information Not Inserted");
                }
            } catch (SQLException ex) {
                Logger.getLogger(StudentRegistrationJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            ErrorMessages.setText("Student Name Should not be blank");
        }
        jText_SName.setText("");
        jText_SId.setText("");
    }//GEN-LAST:event_jButton_InsertActionPerformed

    private void jButton_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_UpdateActionPerformed
        // TODO add your handling code here:
        String query = "UPDATE STUDENT SET NAME='" + jText_SName.getText() + "',DEPARTMENT='" + jCombo_SDept.getSelectedItem() + "',SID=" + jText_SId.getText() + " WHERE SID = " + jText_SId.getText();

        Connection con = JavaConnectDB.getConnection();
        Statement st;

        if (jTable_Student.getSelectedRow() == -1) {
            ErrorMessages.setText("You must Select a row to update");
        } else {
            DefaultTableModel model = (DefaultTableModel) jTable_Student.getModel();
            if (!jText_SName.getText().trim().equals("")) {
                try {
                    st = con.createStatement();
                    if ((st.executeUpdate(query)) == 1) {
                        model.setRowCount(0);
                        showStudentList();
                        ErrorMessages.setText("Student Information Successfully Updated");
                    } else {
                        ErrorMessages.setText("Student Information Not Updated");
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(StudentRegistrationJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }

            } else {
                ErrorMessages.setText("Student Name Should not be blank");
            }
        }
        jText_SName.setText("");
        jText_SId.setText("");
    }//GEN-LAST:event_jButton_UpdateActionPerformed

    private void jTable_StudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_StudentMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable_Student.getModel();
        jText_SName.setText(model.getValueAt(jTable_Student.getSelectedRow(), 0).toString());
        jCombo_SDept.setSelectedItem(model.getValueAt(jTable_Student.getSelectedRow(), 1).toString());
        jText_SId.setText(model.getValueAt(jTable_Student.getSelectedRow(), 2).toString());

    }//GEN-LAST:event_jTable_StudentMouseClicked

    private void jButton_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DeleteActionPerformed
        // TODO add your handling code here:
        String query = "DELETE FROM STUDENT WHERE SID = " + jText_SId.getText();

        Connection con = JavaConnectDB.getConnection();
        Statement st;

        if (jTable_Student.getSelectedRow() == -1) {
            ErrorMessages.setText("You must Select a row to Delete");
        } else {
            DefaultTableModel model = (DefaultTableModel) jTable_Student.getModel();
            try {
                st = con.createStatement();
                if ((st.executeUpdate(query)) == 1) {
                    model.setRowCount(0);
                    showStudentList();
                    ErrorMessages.setText("Student Information Successfully Deleted");
                } else {
                    ErrorMessages.setText("Student Information Not Deleted");
                }
            } catch (SQLException ex) {
                Logger.getLogger(StudentRegistrationJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        jText_SName.setText("");
        jText_SId.setText("");

    }//GEN-LAST:event_jButton_DeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentRegistrationJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentRegistrationJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentRegistrationJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentRegistrationJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentRegistrationJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ErrorMessages;
    private javax.swing.JButton jButton_Delete;
    private javax.swing.JButton jButton_Insert;
    private javax.swing.JButton jButton_Update;
    private javax.swing.JComboBox jCombo_SDept;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Student;
    private javax.swing.JTextField jText_SId;
    private javax.swing.JTextField jText_SName;
    // End of variables declaration//GEN-END:variables
}
